### ISSUE TITLE
launch data to db

### ISSUE THREAD

**Issue by yuvalmargules** [beyond-io/tutor#100]
when vagrant is up, db will be already launched with data one can choose from

**Comment by mosesnagar** [comment]
@yuvalmargules @LiorRey  Is that issue duplicates #98 ?

**Comment by yuvalmargules** [comment]
@mosesnagar nope. I think he meant when a new user registers, a list of courses will be shown at which the user can choose from. correct my if I'm wrong @LiorRey . 
What this issue was meant to be is the data that will be already exist in the database when app is launched.

**Comment by LiorRey** [comment]
Correct @yuvalmargules

**Comment by mosesnagar** [comment]
@yuvalmargules @LiorRey OK I see, the word "demo" confused me. I'll add a description to that issue to make it more clear.
