### ISSUE TITLE
Backend TO-DO in Tutor

### ISSUE THREAD

**Issue by LiorRey** [beyond-io/tutor#11]
- Make a generic page for handling the relevant information about a single course.
   * Create a route for fetching that information from the DB using a suitable controller.
- Make a page for handling and displaying information about all subscribed courses of a user.
   * Create a route for fetching the basic information of each course shown in this page. Fetching from the DB with a controller.

**Comment by mosesnagar** [comment]
#22 
look at that PR. I create a controller to handle single course page. The things needs to be handled is creating Course and Resource model (will be on different issue) and to fill the other functions, so we won't use a dummy data.

**Comment by mosesnagar** [comment]
No need, split to many issues.
