### ISSUE TITLE
Database for Tutor

### ISSUE THREAD

**Issue by golan13** [beyond-io/tutor#12]
Would love for your input in setting up the DB for our app.
The current configuration for the DB is as follows:

Users -
ID int auto_increment Primary Key
FirstName varchar(255)
LastName varchar(255)
Email varchar(255)
Degree int Foreign Key
School int Foreign Key

LookupCategories - 
ID int auto_increment Primary Key
Category varchar(255)

LookupValues - 
ID int auto_increment Primary Key
CategoryID in Foreign Key
Value varchar(255)

Resources - 
ID int auto_increment Primary Key
CourseID int Foreign Key
UserID int Foreign Key
Tags int Foreign Key
Timestamp datetime
Data varchar(2047)

A few things to note:
Users table - do we need also a hash column to store the password hash?
In the LookupCategories table we will have categories for school, degrees and courses. 
In the LookupValues table we will have a list of all schools, degrees and courses available in the app.
In the Resources table we will hold all of the actual data relevant to each course.

**Comment by mosesnagar** [comment]
Users - yes, we need a column for the password, to compare when a use is trying to log in. I think we also will need a column for the user token, but that depends how we will handle the all thing.
LookupCategories, LookupValues  - why we need those? we can create schools, courses and degrees tables with a name column and connect them with each other and with resources table. That way we can use the ORM better, with relationship between all the tables.
Resources - maybe we can add a "description" column so we can show it beside the link on the course page. Also we can create "tags" table, and connect between resources and tags with "many-to-many" relation. That also can be handled with the ORM.

**Comment by golan13** [comment]
This issue was divided into multiple, more descriptive issues.
Closing this issue.
