### ISSUE TITLE
Setting up a guideline 

### ISSUE THREAD

**Issue by mosesnagar** [beyond-io/tutor#8]
To keep our repository organized, I recommend to set principles we all follow. Feel free to comment and add your own ideas.

### Issues
As mentioned on slack, there is already guideline for issues on SOW. Use project-board to handle issues status.
We also will create issues for discussions on things that will affect our app, like DB models, what linter we will use or is we should upload our app to AWS or other cloud. One discussion I can think of its 'how users will login'(for my opinion the authentication can wait until the first MVP, because its not a core in our app, but for that we have a discussion and we all need to decide).

### PRs and branches
- On the PR's description, start with mentioned the issue. Use '#' and just choose the right issue or fill the issue's id.
- The name of the new branch might start with #issueid#desciprtion_of_branch, so we will have one branch per issue. 
For example: 153_creating_login_page

#### linter and coding style
We need to pick a linter for our code. A linter is a tool that help us write code with the same conventions. We will follow styling rules to make all our code and files look the same, what will help check them and keep the order. I saw that what recommended are flake8 and pylint - but feel free to look for others. We will use a linter as part of our CI and in our IDE. 

#### routes and controllers
To keep the backend synchronized with the frontend, we need to talk one language. So I recommend that GET routes will always return templates(using render_template function) and POST routes always return a JSON. That way, the frontend will know what it gets for every request. So GET routes its for representing a view to the user, and POST routes its for getting data from the backend.
Also, recommend to keep routes short, maybe even use rest-api rules.

#### MVC design
For now the app is design to support kinda MVC design(some called it an architecture). We have routes that connect to the controllers, we have views(templates folder) and models(models.py file). I think its a good design, and for what I know its the most popular way for monolith fullstack apps for a very long time.

So feel free to comment and share your own ideas :)  After we all will agree on things we will write all down so we will remember.

**Comment by tbrisker** [comment]
Once there is agreement on the guidelines, they should live in CONTRIBUTING.md - see https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors.
Perhaps convert this proposal to a PR already so people can comment on specific lines?

**Comment by mosesnagar** [comment]
> Once there is agreement on the guidelines, they should live in CONTRIBUTING.md - see https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors.
> Perhaps convert this proposal to a PR already so people can comment on specific lines?

Good idea, #9 .

**Comment by mosesnagar** [comment]
merged.
